### ISSUE TITLE
Will this project use full GTK+?

### ISSUE THREAD

**Issue by Uramekus** [LegendaryClient/Sightstone.Mono#1]
I think GTK is not the ideal toolkit for an LoL client that preserves an near "native" feeling, and there is more options for use with mono like QTsharp that is more functional and faster than GTK.

There is any plans for implementing it in any other toolkit?|
or should i fork it?

**Comment by nairaner** [comment]
I was hoping to get some basic UI working and start on backend. I didn't think about it too much and GTK was by default with MonoDevelop, which was the main reason for choosing it. I used neither GTK nor Qt, but I also found some info about Qtsharp being very basic, so I didnt even try using Qt.

If you would like to contribue in any way, we will be happy to accept any pull requests and might allow you to join our team

**Comment by eddy5641** [comment]
Just make sure that you get the mac lol location
